### ISSUE TITLE
What should the curves be like?

### ISSUE THREAD

**Issue by haonanhe** [YBZh/SymNets#6]
If I train my SymNets successfully, then what should be the curves be like?
I'm really confused cause my network seems to work poorly.
Should the Cst catagory loss/loss_classification/loss_G keeps falling? 
What should the domain loss be like?
Thanks.

**Comment by YBZh** [comment]
The "loss_task_s_Cs" and "loss_task_s_Ct" should keep decreasing to a low level. 
The "loss_domain_st_Cst_part1" and "loss_domain_st_Cst_part2" should decrease at the beginning, gradually increase due to the adversarial training, and end with a medium level. 
The change of "loss_category_st_G" and "loss_domain_st_G" should be opposite to the loss of "Cst_part1 & Cst_part2". 

The change of "loss_classifier" and "loss_G" is complex and determined by the above elements.

**Comment by haonanhe** [comment]
Oh, I got it. Thx for ur reply.
